### PR TITLE
Bump to V0.40.0

### PR DESCRIPTION
**Pull request by sdvillal**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Also we probably should bump the pin in conda-forge-pinning. No ABI laboratory info yet.
https://abi-laboratory.pro/?view=timeline&l=pixman

### CODE REVIEW

**Comment by sdvillal** [comment]
@conda-forge-admin, please rerender

**Comment by sdvillal** [comment]
@conda-forge-admin, please rerender

**Comment by sdvillal** [comment]
@conda-forge/pixman could it be possible to merge this as a first step towards updating pixman in the CF stack? The currently shipped version has some bugs affecting several downstream libraries.

**Comment by ocefpaf** [comment]
Thanks @sdvillal!

**Comment by ocefpaf** [comment]
BTW, consider adding yourself as a maintainer here so you can merge updates like this one ;-p

**Comment by sdvillal** [comment]
Happy to volunteer, how do we do it without forcing a new build?

And a question, how would we update the pin? Will the bot open a PR automagically in conda-forge-pinnning?

**Comment by ocefpaf** [comment]
> Happy to volunteer, how do we do it without forcing a new build?

You can skip CI but the hash mechanism should be robust enough to now create a new package just for a new maintainer. However, some people do like the new package so their name get into the package metadata. No strong opinions on my side, whatever you choose is fine with me.

> And a question, how would we update the pin? Will the bot open a PR automagically in conda-forge-pinnning?

In theory it should. If not you can issue one yourself. We no longer update the pin directly, now we do a "migration" to the new pin and then close it when all the dependencies are built and update the pin.

**Pull request merged**
